global:
  scrape_interval:     15s

scrape_configs:

  - job_name: 'springboot-cloud-actuator'

    scrape_interval: 5s

    metrics_path: "/actuator/prometheus"

    static_configs:
      - targets: ['springboot-cloud-app:8080']
